# Generated by Django 5.2.11 on 2026-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
